# Copyright 2025 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""AgentDyn environment tool - exposes AgentDyn functions per scenario.

This tool wraps all functions from an AgentDyn TaskSuite scenario (shopping,
github, dailylife, etc.) into a single dispatcher tool. The LLM calls it with:

{
    "tool_name": "search_products",
    "args": {"query": "laptop"}
}

The tool routes to the underlying FunctionsRuntime and updates the environment.
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Optional
from uuid import uuid4

from agentdojo.task_suite.load_suites import get_suite

from verl.tools.base_tool import BaseTool
from verl.tools.schemas import OpenAIFunctionToolSchema, ToolResponse
from verl.utils.rollout_trace import rollout_trace_op

from .shared_state import (
    AgentDynSharedState,
    get_shared_state,
    register_shared_state,
    release_shared_state,
)

logger = logging.getLogger(__name__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class AgentDynTool(BaseTool):
    """A tool that dispatches calls to AgentDyn functions for a scenario.

    Each scenario (shopping, github, dailylife) has its own tool instance.
    All function calls within a trajectory share the same AgentDynSharedState.
    """

    # Registry to track which instance_id maps to which suite
    _suite_name: str

    def __init__(
        self,
        config: dict,
        tool_schema: OpenAIFunctionToolSchema,
        suite_name: str = "shopping",
    ):
        """Initialize the AgentDyn tool.

        Args:
            config: Tool config dict.
            tool_schema: OpenAI function schema for this tool.
            suite_name: AgentDyn suite name (shopping, github, dailylife, etc.).
        """
        super().__init__(config, tool_schema)
        self._suite_name = suite_name
        self._suite = get_suite(suite_name)

    @classmethod
    def create_schema_for_suite(cls, suite_name: str) -> OpenAIFunctionToolSchema:
        """Generate OpenAI tool schema for a suite.

        The schema describes a dispatcher that takes tool_name and args.
        """
        return OpenAIFunctionToolSchema.model_validate({
            "type": "function",
            "function": {
                "name": f"agentdyn_{suite_name}",
                "description": (
                    f"Execute tools for the {suite_name} scenario. "
                    "Call with tool_name and args to interact with the environment."
                ),
                "parameters": {
                    "type": "object",
                    "properties": {
                        "tool_name": {
                            "type": "string",
                            "description": "Name of the tool to call (e.g., search_products, send_email)",
                        },
                        "args": {
                            "type": "object",
                            "description": "Arguments for the tool call",
                            "additionalProperties": True,
                        },
                    },
                    "required": ["tool_name", "args"],
                },
            }
        })

    async def create(
        self,
        instance_id: Optional[str] = None,
        user_task_id: str = "user_task_1",
        injection_task_id: Optional[str] = None,
        injections: Optional[dict[str, str]] = None,
        **kwargs,
    ) -> tuple[str, ToolResponse]:
        """Create a tool instance for a trajectory.

        Args:
            instance_id: Unique identifier for this trajectory.
            user_task_id: AgentDyn user task ID (e.g., "user_task_1").
            injection_task_id: AgentDyn injection task ID (e.g., "injection_task_1").
                              If None, no injection is applied.
            injections: Dict of injection content. Usually generated by attack.

        Returns:
            Tuple of (instance_id, ToolResponse).
        """
        if instance_id is None:
            instance_id = str(uuid4())

        # Create shared state for this trajectory
        state = AgentDynSharedState.from_task_config(
            suite=self._suite,
            user_task_id=user_task_id,
            injection_task_id=injection_task_id,
            injections=injections,
        )
        register_shared_state(instance_id, state)

        # Return empty ToolResponse (environment is already set up)
        return instance_id, ToolResponse()

    @rollout_trace_op
    async def execute(
        self,
        instance_id: str,
        parameters: dict[str, Any],
        **kwargs,
    ) -> tuple[ToolResponse, float, dict]:
        """Execute a tool call.

        Args:
            instance_id: The trajectory instance ID.
            parameters: Dict with "tool_name" and "args" keys.

        Returns:
            Tuple of (ToolResponse, step_reward, metrics).
        """
        state = get_shared_state(instance_id)

        tool_name = parameters.get("tool_name", "")
        args = parameters.get("args", {})

        if not tool_name:
            return ToolResponse(text="Error: tool_name is required"), 0.0, {"error": True}

        # Execute the function
        result_str, error = state.execute_function(tool_name, args)

        if error:
            return ToolResponse(text=f"Error: {error}"), 0.0, {"error": True, "tool_name": tool_name}

        # No intermediate reward - reward is computed at trajectory end
        return ToolResponse(text=result_str), 0.0, {"tool_name": tool_name, "error": False}

    async def calc_reward(self, instance_id: str, **kwargs) -> float:
        """Calculate the final reward for the trajectory.

        Returns:
            Total reward (utility + security + sandbox bonus).
        """
        state = get_shared_state(instance_id)
        rewards = state.compute_reward()
        return rewards["total_reward"]

    async def release(self, instance_id: str, **kwargs) -> None:
        """Release the tool instance and clean up state."""
        release_shared_state(instance_id)

    def get_available_tools(self) -> list[str]:
        """Return list of available tool names in this suite."""
        return list(self._suite.tools.keys())

    def get_tool_schemas(self) -> list[dict]:
        """Return OpenAI-style schemas for all tools in the suite.

        This can be used to populate the tools list in the prompt.
        """
        schemas = []
        for func in self._suite.tools.values():
            # Convert AgentDyn Function to OpenAI schema
            schema = {
                "type": "function",
                "function": {
                    "name": func.name,
                    "description": func.description,
                    "parameters": {},
                }
            }
            # Get parameters from Pydantic model
            if hasattr(func.parameters, "model_json_schema"):
                param_schema = func.parameters.model_json_schema()
                schema["function"]["parameters"] = param_schema
            schemas.append(schema)
        return schemas
